// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $("#start-button").click(function() {
      var game;
      game = new Game();
      game.start();
      return game.render();
    });
  });

  this.Game = (function() {
    function Game() {
      this.scene = new THREE.Scene();
      this.camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
      this.renderer = new THREE.WebGLRenderer();
    }

    Game.prototype.start = function() {
      var f_texture, geometry, material;
      this.renderer.setSize(window.innerWidth, window.innerHeight);
      document.body.appendChild(this.renderer.domElement);
      f_texture = new THREE.ImageUtils.loadTexture('image/f.png');
      geometry = new THREE.CubeGeometry(1, 1, 1);
      material = new THREE.MeshPhongMaterial({
        map: f_texture
      });
      this.cube = new THREE.Mesh(geometry, material);
      this.scene.add(this.cube);
      return this.camera.position.z = 5;
    };

    Game.prototype.render = function() {
      var _this = this;
      requestAnimationFrame(function() {
        return _this.render();
      });
      this.cube.rotation.x += 0.1;
      this.cube.rotation.y += 0.1;
      return this.renderer.render(this.scene, this.camera);
    };

    return Game;

  })();

}).call(this);
